import '../models/models.dart';
import 'share.dart';
import 'time_utils.dart';

final RegExp _assUnsafeStyleNamePattern = RegExp(r'[\r\n,]');
final RegExp _assHeaderNewlinePattern = RegExp(r'[\r\n]+');

/// 对齐Python版 `converter/ass.py::ass_converter`。
String assConverter({
  required String? title,
  required int? durationMs,
  required MultiLyricsData lyricsData,
  required Map<String, Map<int, int>> langsMapping,
  required List<String> langsOrder,
  required String lddcVersion,
}) {
  final Map<String, String> styleNameByLanguage = _buildAssStyleNames(
    langsOrder,
  );
  final StringBuffer buffer = StringBuffer()
    ..write('[Script Info]\n')
    ..write('; Script generated by LDDC $lddcVersion\n')
    ..write('; https://github.com/chenmozhijin/LDDC\n');
  if (title != null) {
    final String safeTitle = _sanitizeAssHeaderValue(title);
    if (safeTitle.isNotEmpty) {
      buffer.write('Title: $safeTitle\n');
    }
  }
  buffer
    ..write(
      'ScriptType: v4.00+\n'
      'Timer: 100.0000\n'
      '\n'
      '[V4+ Styles]\n'
      'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
      'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, '
      'ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, '
      'Alignment, MarginL, MarginR, MarginV, Encoding\n',
    )
    ..write(
      langsOrder
          .map((String lang) {
            final String styleName = styleNameByLanguage[lang]!;
            return 'Style: $styleName,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1';
          })
          .join('\n'),
    )
    ..write('\n\n')
    ..write('[Events]\n')
    ..write(
      'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n',
    );

  final LyricsData? origLyrics = lyricsData['orig'];
  if (origLyrics == null || origLyrics.isEmpty) {
    return buffer.toString();
  }

  final int? resolvedDuration =
      durationMs ??
      (origLyrics.last.startMs == null
          ? null
          : origLyrics.last.startMs! + 5000);
  final LyricsData fullOrigLyrics = getFullTimestampsLyricsData(
    origLyrics,
    durationMs: resolvedDuration,
    onlyLine: true,
  );

  final Map<String, StringBuffer> textByLang = <String, StringBuffer>{
    for (final String lang in langsOrder.reversed) lang: StringBuffer(),
  };
  for (int origIndex = 0; origIndex < fullOrigLyrics.length; origIndex += 1) {
    final LyricsLine origLine = fullOrigLyrics[origIndex];
    final int? start = origLine.startMs;
    final int? end = origLine.endMs;
    if (start == null || end == null || end < start) {
      continue;
    }

    final List<ConverterLyricsLine> lines = getLyricsLines(
      lyricsData: lyricsData,
      langsOrder: langsOrder,
      origIndex: origIndex,
      origLine: origLine,
      langsMapping: langsMapping,
    );
    for (final ConverterLyricsLine item in lines) {
      final String lang = item.lang;
      final String? styleName = styleNameByLanguage[lang];
      if (styleName == null) {
        continue;
      }
      textByLang[lang]?.write(
        'Dialogue: 0,${msToAssTimestamp(start)},${msToAssTimestamp(end)},'
        '$styleName,,0,0,0,,${_lyricsLineToAssText(item.line)}\n',
      );
    }
  }

  for (final String lang in langsOrder.reversed) {
    buffer.write(textByLang[lang].toString());
  }
  return buffer.toString();
}

/// 对齐Python版 `converter/ass.py::lyrics_line2asstext`。
String _lyricsLineToAssText(LyricsLine lyricsLine) {
  if (lyricsLine.words.length == 1) {
    return _escapeAssText(joinLineText(lyricsLine, includeEmpty: false));
  }
  final StringBuffer buffer = StringBuffer();
  for (final LyricsWord word in lyricsLine.words) {
    final int? start = word.startMs;
    final int? end = word.endMs;
    if (start == null || end == null) {
      return _escapeAssText(joinLineText(lyricsLine, includeEmpty: false));
    }
    final int k = (end - start).abs() ~/ 10;
    buffer.write('{\\kf$k}${_escapeAssText(word.text)}');
  }
  return buffer.toString();
}

Map<String, String> _buildAssStyleNames(List<String> languages) {
  final Map<String, String> result = <String, String>{};
  final Set<String> usedNames = <String>{};
  for (final String language in languages) {
    final String normalized = language
        .replaceAll(_assUnsafeStyleNamePattern, '_')
        .trim();
    final String baseName = normalized.isEmpty ? 'LDDC' : normalized;
    String candidate = baseName;
    int suffix = 2;
    while (!usedNames.add(candidate)) {
      candidate = '${baseName}_$suffix';
      suffix += 1;
    }
    result[language] = candidate;
  }
  return result;
}

String _sanitizeAssHeaderValue(String value) {
  return value.replaceAll(_assHeaderNewlinePattern, ' ').trim();
}

String _escapeAssText(String text) {
  // ASS 会把反斜杠命令和花括号内容解释为换行、空格或样式覆盖指令。
  // 先保护歌词中的字面反斜杠与花括号，再把真实换行转换为 ASS 的显式换行，
  // 可以避免普通歌词意外改变后续文本布局或注入样式标签。
  final String normalizedNewlines = text
      .replaceAll('\r\n', '\n')
      .replaceAll('\r', '\n');
  return normalizedNewlines
      .replaceAll('\\', r'\\')
      .replaceAll('{', r'\{')
      .replaceAll('}', r'\}')
      .replaceAll('\n', r'\N');
}
